export const initialState = {
  data: [],
  loading: true,
  category: "any",
  type: "any",
  difficulty: "any",
  amount: 5,
  categoryText: "any",
  difficultyText: "any",
  typeText: "any",
  score: 0,
  answersChecked: false,
  quizStarted: false,
  isChoosingOptions: false,
  categoryOpen: false,
  difficultyOpen: false,
  typeOpen: false,
  allAnswersSelected: true,
};
